name: Git commit

on:
  #push:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  diags:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
   
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'repository_dispatch'
        with:
          ref: refs/pull/${{ github.event.client_payload.pull_request.number }}/head
      - uses: actions/checkout@v2
        if: github.event_name != 'repository_dispatch'
      - name: Dump commit ref (testing if PR or not)
        run: |
          echo "github.event.client_payload.pull_request.head.ref=${{ github.event.client_payload.pull_request.head.ref }}."
          echo "github.event_name=${{ github.event_name }}."
          echo "GITHUB_SHA=$GITHUB_SHA."
          git status
          git log -n 3
      - name: Write the markdown file
        run: |
          #echo "::set-output name=date::$(date)"
          printf "Hello World\n" > helloworld.md
          cat hellworld.md
      - name: Commit the updated markdown file
        if: github.event_name != 'pull_request' && github.event_name != 'repository_dispatch'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit helloworld.md -m "Automated update for helloworld.md."
          git push
