name: Matrix Record Results Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [matrix-test-command]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs
jobs:
  # Job Description: Performs the Data Channel Test between each combination of the client and server for each library.
  interoptests:
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      result_a_c: ${{ steps.maintask.outputs.result_a_c }}
      result_a_d: ${{ steps.maintask.outputs.result_a_d }}
      result_b_c: ${{ steps.maintask.outputs.result_b_c }}
      result_b_d: ${{ steps.maintask.outputs.result_b_d }}

    strategy:
      matrix:
        server: ["a", "b"]
        client: ["c", "d"]

    steps:
      - name: Run main task
        id: maintask
        run: |
          # Store output
          result=1
          echo "result_${{ matrix.server }}_${{ matrix.client }}=${result}" >> "$GITHUB_OUTPUT"

  collate:
    runs-on: ubuntu-latest
    needs: [interoptests]
    
    steps:
      - name: Collate
        run: |
          echo "Collating..."
          echo "The output from interop-test is: ${{ toJSON(needs.interoptests.outputs) }}"
          results='${{ toJSON(needs.interoptests.outputs) }}'
          echo "The output from interop-test (2) is: ${results}"
          
          echo "${results}" | jq -r 'to_entries | .[] | "\(.key): \(.value)"'