name: Matrix Record Results Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [matrix-test-command]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs
jobs:
  # Job Description: Performs the Data Channel Test between each combination of the client and server for each library.
  interop-tests:
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      output1: ${{ steps.maintask.outputs.result }}

    strategy:
      matrix:
        server: ["sipsorcery", "werift"]
        client: ["sipsorcery", "werift"]

    steps:
      - name: Run main task
        id: maintask
        run: |
          # Store output
          echo "result=${{ matrix.server }},${{ matrix.client }}" >> $GITHUB_OUTPUT

  collate:
    runs-on: ubuntu-latest
    needs: [interop-tests]
    
    steps:
      - name: Collate
        run: |
          echo "Collating..."
          echo "The output from interop-test is: ${{ needs.interop-tests.outputs.output1 }}"
