name: Matrix Record Results Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [matrix-test-command]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Job Description: Performs the Data Channel Test between each combination of the client and server for each library.
  interop-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server: ["libdatachannel", "sipsorcery", "werift"]
        client: ["libdatachannel", "sipsorcery", "werift"]

    steps:
      - name: Set output results
        id: set_output
        run: |
          # Store output
          echo "${{ matrix.server }},${{ matrix.client }}"

  collate:
    runs-on: ubuntu-latest
    needs: [interop-tests]
    steps:
     run: |
      echo "Collating..."
