name: Update Markdown

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  winjob:
    runs-on: windows-latest
    steps:
      - name: Get OS version
        shell: pwsh
        run: |
          $x = Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer | ft -HideTableHeaders
          echo $x
          echo $x >> winjob.txt
      - name: Upload result for winjob
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: winjob.txt
          
  macjob:
    runs-on: macOS-latest
    steps:
      - name: Get OS version
        run: |
          x=$(uname -a)
          echo $x
          echo $x >> macjob.txt
      - name: Upload result for macjob
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: macjob.txt
    
  collate:
    runs-on: ubuntu-latest
    needs: [ winjob, macjob ]
    steps:
      - uses: actions/checkout@v2
      - name: Download results
        uses: actions/download-artifact@v2
        with:
          name: results
      - name: Collate result files
        run: |
          ls
      - name: Commit the updated markdown file
        run: |
          #echo "::set-output name=date::$(date)"
          echo "GitHub Actions OS Versions at $(date)" >> test.md
          cat winjob.txt >> test.md
          cat macjob.txt >> test.md
          cat test.md
          git config --global user.name "GitHub Action (update-md)"
          git commit test.md -m "Automated update for test.md."
          git push
