name: Update OS Versions Markdown

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  winjob:
    runs-on: windows-latest
    steps:
      - name: Get OS version
        shell: pwsh
        run: |
          $x = Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer | ft -HideTableHeaders
          echo $x
          echo $x >> winjob.txt
      - name: Upload result for winjob
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: winjob.txt
          
  macjob:
    runs-on: macOS-latest
    steps:
      - name: Get OS version
        run: |
          x=$(uname -a)
          echo $x
          echo $x >> macjob.txt
      - name: Upload result for macjob
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: macjob.txt
    
  ubuntujob:
    runs-on: ubuntu-latest
    steps:
      - name: Get OS version
        run: |
          x=$(uname -a)
          echo $x
          echo $x >> ubuntujob.txt
      - name: Upload result for ubuntujob
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ubuntujob.txt
    
  collate:
    runs-on: ubuntu-latest
    needs: [ winjob, macjob, ubuntujob ]
    steps:
      - uses: actions/checkout@v2
      - name: Download results
        uses: actions/download-artifact@v2
        with:
          name: results
      - name: Collate result files
        run: |
          ls
      - name: Commit the updated markdown file
        run: |
          #echo "::set-output name=date::$(date)"
          printf "GitHub Actions OS Versions at $(date)\n" > osversions.md
          printf "**windows-latest**\n" >> osversions.md
          printf "> $(cat winjob.txt | grep -v '^[[:space:]]*$')\n\n" >> osversions.md
          printf "**macOS-latest**\n" >> osversions.md
          printf "> $(cat macjob.txt)\n\n" >> osversions.md
          printf "**ubuntu-latest**\n" >> osversions.md
          printf "> $(cat ubuntujob.txt)\n\n" >> osversions.md
          cat osversions.md
          git config --global user.name "GitHub Action (update-md)"
          git commit osversions.md -m "Automated update for osversions.md."
          git push
